### ISSUE TITLE
How to get navigation to work

### ISSUE THREAD

**Issue by nickGermi** [photokandyStudios/PKNativeControls#1]
I'm using latest version of Cordova and your plug-in developing for ios7 platform, following is my index.html file

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, target-densitydpi=device-dpi" />
        <link rel="stylesheet" type="text/css" href="css/index.css" />
        <title>Hello World</title>
    </head>
    <body>
        <div>
         test<br>test<br>test<br>test<br>test<br>test<br>test<br>test<br>test<br>test<br>test<br>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript">
            document.addEventListener("deviceready", function(){
              var navigationBar = window.nativeControls.NavigationBar();
              navigationBar.tintColor = window.nativeControls.Color ( "red" );
              navigationBar.barTintColor = window.nativeControls.Color ( "white" );
              navigationBar.addToView();
              var navigationBarItem = window.nativeControls.NavigationBarItem();
              navigationBarItem.title = "View Title";
            });
        </script>
    </body>
</html>
```

And this is what I get in the simulator:

![screen shot 2014-01-22 at 12 52 09 am](https://f.cloud.github.com/assets/4242017/1963826/46728d54-82a3-11e3-94be-6d4f116fc201.png)

As it can be seen, "View Title" is not showing up, am I doing something wrong?

**Comment by kerrishotts** [comment]
I don't see code to push the navigation item onto the bar. Add this and see if it works:

navigationBar.push (navigationItem);

That will push the navigation item into the bar's hierarchy, and should render the title. While you can change the title by changing the item's title, it won't result in any animation. To get the navigation bar's animation, use the push/pop methods with new navigation items. 

Sent from my phone. 

---

Kerri Shotts
photoKandy Studios, LLC

On the Web: http://www.photokandy.com/

Social Media:
          Twitter: @photokandy, http://twitter.com/photokandy
          Tumblr: http://photokandy.tumblr.com/
          Github: https://github.com/kerrishotts
                        https://github.com/organizations/photokandyStudios
          CoderWall: https://coderwall.com/kerrishotts

Apps on the Apple Store:
          https://itunes.apple.com/us/artist/photokandy-studios-llc/id498577828

Books:
         http://www.packtpub.com/phonegap-2-mobile-application-hotshot/book
          http://www.packtpub.com/phonegap-social-app-development/book

**Comment by nickGermi** [comment]
That didn't work it is still blank, only thing I've been able to change is the colour of the navigation bar.

By the way I assume you meant 

```
navigationBar.push(navigationBarItem);
```

I've also tried 

```
navigationBar.push(navigationBarItem.title);
```

**Comment by nickGermi** [comment]
However this worked:

```
            document.addEventListener("deviceready", function(){
              var navigationBar = window.nativeControls.NavigationBar();
              navigationBar.tintColor = window.nativeControls.Color ( "red" );
              navigationBar.barTintColor = window.nativeControls.Color ( "white" );
              navigationBar.addToView();
              var navigationItem = window.nativeControls.NavigationItem();
              navigationItem.title = "View Title";
              navigationBar.push(navigationItem);
            });
```

It looks great so far, I guess the instructions in the readme file needs to be updated :)

**Comment by kerrishotts** [comment]
Glad you got it working. The .push() is required, so I was more focused on that than waiting for the document ready event. Interesting that the navigation bar can be rendered, but the navigation item can't when not waiting -- perhaps the cordova bridge is only partially initialized, and the second request somehow fails.

I generally have boilerplate code that includes the document ready event, so it is easy to forget. I'll have add it to the docs. (I need better docs anyway. Maybe via the wiki pages. )

Let me know if there are any particular features you'd like to see - just because it may satisfy my needs doesn't mean it will do the same for others. :) I do know of a few things I want to add, including better error handling (right now, you are more likely to get a crash with a bad parameter), and better integration with promises when dealing with returning values (like a view's frame) over the bridge. But if you think of anything else, I'm happy to consider it. 

Sent from my phone. 

---

Kerri Shotts
photoKandy Studios, LLC

On the Web: http://www.photokandy.com/

Social Media:
          Twitter: @photokandy, http://twitter.com/photokandy
          Tumblr: http://photokandy.tumblr.com/
          Github: https://github.com/kerrishotts
                        https://github.com/organizations/photokandyStudios
          CoderWall: https://coderwall.com/kerrishotts

Apps on the Apple Store:
          https://itunes.apple.com/us/artist/photokandy-studios-llc/id498577828

Books:
         http://www.packtpub.com/phonegap-2-mobile-application-hotshot/book
          http://www.packtpub.com/phonegap-social-app-development/book

**Comment by nickGermi** [comment]
In the docs you have 

```
var navigationBarItem = window.nativeControls.NavigationBarItem();
```

But it should be 

```
var navigationBarItem = window.nativeControls.NavigationItem();
```

It's a type I believe

And I'm still trying to get the basic functions working, having some trouble with the buttons at the moment, I guess it would be beneficial for everyone if you could perhaps create a basic demo with all the current functions, this is my first attempt in invoking native controls, never coded in Objective-C and this is a bit confusing for me.

By the way, reason I'm trying to use native controls (apart from being a better option) is the 10MB memory limit on WebView on Apple devices, I guess by using your plugin any memory consumed by these controls is not counted as memory used by WebView am I right?

**Comment by kerrishotts** [comment]
What trouble are you having with the buttons?

Sent from my phone. 

---

Kerri Shotts
photoKandy Studios, LLC

On the Web: http://www.photokandy.com/

Social Media:
          Twitter: @photokandy, http://twitter.com/photokandy
          Tumblr: http://photokandy.tumblr.com/
          Github: https://github.com/kerrishotts
                        https://github.com/organizations/photokandyStudios
          CoderWall: https://coderwall.com/kerrishotts

Apps on the Apple Store:
          https://itunes.apple.com/us/artist/photokandy-studios-llc/id498577828

Books:
         http://www.packtpub.com/phonegap-2-mobile-application-hotshot/book
          http://www.packtpub.com/phonegap-social-app-development/book

**Comment by kerrishotts** [comment]
As to the memory limit, I'm not entirely sure that the native controls will help -- namely because there are no data controls at the moment (such as lists or tables). Since the content is still rendered in the web view, the only memory you are partially saving is for your chrome. (And it may not save memory anyway: each native object has a JS object and a corresponding native object. Unless a DOM element outweighs both objects, it will be a net loss.)

Based on what I can see, native controls themselves won't offer any real memory savings. The 10mb limit applies to JS allocations, so the native objects may not count against it, but you'd still have the JS objects hanging around. (If we added a table view, I could see that an array of JS strings could be smaller than their DOM analogs, but that isn't around yet.)

Also: be sure to .destroy() objects you don't need anymore -- otherwise you'll leak memory like a sieve as the native controls must be explicitly released to free memory. 

Sent from my phone. 

---

Kerri Shotts
photoKandy Studios, LLC

On the Web: http://www.photokandy.com/

Social Media:
          Twitter: @photokandy, http://twitter.com/photokandy
          Tumblr: http://photokandy.tumblr.com/
          Github: https://github.com/kerrishotts
                        https://github.com/organizations/photokandyStudios
          CoderWall: https://coderwall.com/kerrishotts

Apps on the Apple Store:
          https://itunes.apple.com/us/artist/photokandy-studios-llc/id498577828

Books:
         http://www.packtpub.com/phonegap-2-mobile-application-hotshot/book
          http://www.packtpub.com/phonegap-social-app-development/book

**Comment by kerrishotts** [comment]
Updated readme documentation
