### ISSUE TITLE
BarImageButtons coloured by the tintcolor

### ISSUE THREAD

**Issue by medida** [photokandyStudios/PKNativeControls#18]
I'm trying to add a button to my top navigation.
this is on iOS7 at the moment.

```
 var btn_add = window.nativeControls.BarImageButton();
  btn_add.tintColor = window.nativeControls.Color("black"); // this makes the button what colour is entered - here... if missing out the button is just blue!
  btn_add.image = "/www/img/menubutton"; // this is a .PNG image
 navigationItem.rightButtons = [btn_add];
```

my button is added - but instead of showing my image, its showing the right shape, but coloured in with the tint colour.

Should the images be in a specific file type or what am i missing.

Thanks
John

**Comment by kerrishotts** [comment]
Try first by taking the `/` off the path and see if that helps. I'll have to update the documentation to fix that, since I use an absolute path in the docs. My bad.

Also make sure your image has a foreground (this can be any color as this gets replaces with the tint color) and a transparent background. If the entire image is non-transparent, you'll be apt to see a large solid square instead. If you want to send a link to your PNG file or attach it to your comment, that would help me know for sure.

**Comment by medida** [comment]
Hello - I've altered my image to just a simple line drawing with a transparent background and this has worked fine. 
I was attempting to use an image to be the full button - so a rounded image with the icon / text on it.

Thanks 

John
